[package]
name = "glbrowser"
version = "0.0.1"
authors = ["The Servo Project Developers"]

[[bin]]
name = "glbrowser"
path = "main.rs"

[dependencies.servo]
path = "../.."

[dependencies.gfx]
path = "../../components/gfx"

[dependencies.script]
path = "../../components/script"

[dependencies.util]
path = "../../components/util"

[dependencies.azure]
git = "https://github.com/servo/rust-azure"

[dependencies.geom]
git = "https://github.com/servo/rust-geom"

[dependencies.glfw]
git = "https://github.com/servo/glfw-rs"
branch = "servo"

[dependencies.layers]
git = "https://github.com/servo/rust-layers"
